# references:
#   https://hub.docker.com/_/rabbitmq

version: "3.9"

services:
    rabbitmq:
        image: webento/rabbitmq:latest
        container_name: rabbitmq
        restart: unless-stopped
        ports:
            - "1883:1883"
            - "5671:5671"
            - "5672:5672"
            - "15672:15672"
            - "15674:15674"
            - "15675:15675"
            - "15692:15692"
            - "25672:25672"
            - "61613:61613"
        volumes:
            - rabbitmq-volume:${PROJECT_ABSOLUTE_PATH}/data/rabbitmq
        environment:
            RABBITMQ_DEFAULT_VHOST: master
            RABBITMQ_DEFAULT_USER: ipr-user
            RABBITMQ_DEFAULT_PASS: ipr-pass
            # RABBITMQ_ERLANG_COOKIE: EOzFBGMs1AK6E5QIat444
        hostname: rabbitmq
        networks:
            - ipr-network

    postgres:
        container_name: postgres_container
        image: postgres
        environment:
            POSTGRES_USER: ipr-user
            POSTGRES_PASSWORD: ipr-pass
            PGDATA: ${PROJECT_ABSOLUTE_PATH}/data/postgres
        volumes:
            - postgres-volume:${PROJECT_ABSOLUTE_PATH}/data/postgres
        ports:
            - "5433:5432"
        networks:
            - ipr-network
        restart: unless-stopped

    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin-volume:${PROJECT_ABSOLUTE_PATH}/data/pgadmin

        ports:
            - "${PGADMIN_PORT:-5050}:80"
        networks:
            - ipr-network
        restart: unless-stopped

volumes:
    rabbitmq-volume:
        name: rabbitmq-volume
        driver: local
    postgres-volume:
        name: postgres-volume
        driver: local
    pgadmin-volume:
        name: pgadmin-volume
        driver: local

networks:
    ipr-network:
        name: ipr-network
        driver: bridge